name: Ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rubyVersion: [2.5, 2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.rubyVersion }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rubyVersion }}
      - name: Cache gems (Ruby ${{ matrix.rubyVersion }})
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-test-ruby-${{ matrix.rubyVersion }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ matrix.rubyVersion }}
      - name: Install gems (Ruby ${{ matrix.rubyVersion }})
        run: |
          bundle config path vendor/bundle
          bundle config set frozen 'true'
          bundle install --jobs 4 --retry 3
      - name: Run tests (Ruby ${{ matrix.rubyVersion }})
        run: bundle exec rspec
